# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

task :default do
  system "rake -T"
end

desc "org to markdown converter"
task :o2m do # any name on task_name
  org = ARGV[1] || "readme.org"
  md = File.basename(org,".org")+".md"
  # your code goes
  puts comm = "pandoc #{org} -f org -t markdown -o #{md}"
  system comm
  exit
end

