# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

task :default do
  system "rake -T"
end

desc "make md from org"
task :mk_md do # any name on task_name
  file = ARGV[1] || 'readme'
  # your code goes
         system "pandoc #{file}.org -f org -t markdown -o #{file}.md"
  exit
end
